apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  JWT_SECRET: "fiap-tech-challenge-secret"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "oficina_mecanica"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/oficina_mecanica?schema=public"